default:
    SQLALCHEMY_DATABASE_URI: sqlite://data.db
development:
    SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:localhost123@localhost:3306/pyfly
production:
    SQLALCHEMY_DATABASE_URI: postgresql://...